# Generated by Django 5.2.7 on 2025-10-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/avatars", verbose_name="Аватар"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Откуда вы",
                max_length=20,
                null=True,
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Введите номер телефона",
                max_length=10,
                null=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=50, unique=True, verbose_name="Email"),
        ),
    ]
