# Generated by Django 4.2.2 on 2025-10-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_message_mailinglist_attemptmailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="mail_theme",
            field=models.CharField(max_length=100, verbose_name="Тема письма"),
        ),
    ]
