# Generated by Django 4.2.2 on 2025-10-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_message_mail_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="status",
            field=models.CharField(
                help_text="Создана, Запущена, Завершена",
                max_length=9,
                verbose_name="Статус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="time_first",
            field=models.DateTimeField(
                help_text="YYYY-MM-DD HH:MM:SS",
                verbose_name="Дата и время первой отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="time_last",
            field=models.DateTimeField(
                help_text="YYYY-MM-DD HH:MM:SS",
                verbose_name="Дата и время окончания отправки",
            ),
        ),
    ]
