# Generated by Django 4.2.2 on 2025-10-24 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing", "0004_alter_mailinglist_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingget",
            options={
                "ordering": ["email"],
                "permissions": [
                    ("can_moderate_mailing_get", "Can moderate mailing get")
                ],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailinglist",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_moderate_mailing_list", "Can moderate mailing list")
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["mail_theme"],
                "permissions": [("can_moderate_messages", "Can moderate messages")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AddField(
            model_name="mailingget",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="attemptmailing",
            name="status",
            field=models.CharField(
                help_text="Успешно, Не успешно", max_length=10, verbose_name="Статус"
            ),
        ),
    ]
